using System.Collections.Generic;
using UnityEngine;

public static class Constants
{
    /// <summary>
    /// Joints that reflect to unity joints
    /// </summary>
    public static readonly Dictionary<JointType, HumanBodyBones> JointToBone = new()
    {
        {
            JointType.Head,
            HumanBodyBones.Head
        },
        {
            JointType.Neck,
            HumanBodyBones.Neck
        },
        {
            JointType.Chest,
            HumanBodyBones.UpperChest
        },
        {
            JointType.Waist,
            HumanBodyBones.Spine
        },
        {
            JointType.Pelvis,
            HumanBodyBones.Hips
        },
        {
            JointType.ClavicleLeft,
            HumanBodyBones.LeftShoulder
        },
        {
            JointType.ShoulderLeft,
            HumanBodyBones.LeftUpperArm
        },
        {
            JointType.ElbowLeft,
            HumanBodyBones.LeftLowerArm
        },
        {
            JointType.WristLeft,
            HumanBodyBones.LeftHand
        },
        {
            JointType.ClavicleRight,
            HumanBodyBones.RightShoulder
        },
        {
            JointType.ShoulderRight,
            HumanBodyBones.RightUpperArm
        },
        {
            JointType.ElbowRight,
            HumanBodyBones.RightLowerArm
        },
        {
            JointType.WristRight,
            HumanBodyBones.RightHand
        },
        {
            JointType.HipLeft,
            HumanBodyBones.LeftUpperLeg
        },
        {
            JointType.KneeLeft,
            HumanBodyBones.LeftLowerLeg
        },
        {
            JointType.AnkleLeft,
            HumanBodyBones.LeftFoot
        },
        {
            JointType.FootLeft,
            HumanBodyBones.LeftToes
        },
        {
            JointType.HipRight,
            HumanBodyBones.RightUpperLeg
        },
        {
            JointType.KneeRight,
            HumanBodyBones.RightLowerLeg
        },
        {
            JointType.AnkleRight,
            HumanBodyBones.RightFoot
        },
        {
            JointType.FootRight,
            HumanBodyBones.RightToes
        },
        {
            JointType.Xiphoid,
            HumanBodyBones.Chest
        },
        {
            JointType.EarLeft,
            HumanBodyBones.LeftEye
        },
        {
            JointType.EarRight,
            HumanBodyBones.RightEye
        },
    };

    public static readonly Dictionary<JointType, JointType> Bones = new()
    {
        {
            JointType.Pelvis,
            JointType.Waist
        },
        {
            JointType.Waist,
            JointType.Xiphoid
        },
        {
            JointType.Xiphoid,
            JointType.Chest
        },
        {
            JointType.Chest,
            JointType.Neck
        },
        {
            JointType.Neck,
            JointType.Nose
        },
        {
            JointType.ClavicleLeft,
            JointType.ShoulderLeft
        },
        {
            JointType.ShoulderLeft,
            JointType.ElbowLeft
        },
        {
            JointType.ElbowLeft,
            JointType.WristLeft
        },
        {
            JointType.ClavicleRight,
            JointType.ShoulderRight
        },
        {
            JointType.ShoulderRight,
            JointType.ElbowRight
        },
        {
            JointType.ElbowRight,
            JointType.WristRight
        },
        {
            JointType.HipLeft,
            JointType.KneeLeft
        },
        {
            JointType.KneeLeft,
            JointType.AnkleLeft
        },
        {
            JointType.AnkleLeft,
            JointType.FootLeft
        },
        {
            JointType.HipRight,
            JointType.KneeRight
        },
        {
            JointType.KneeRight,
            JointType.AnkleRight
        },
        {
            JointType.AnkleRight,
            JointType.FootRight
        }
    };
}